version: '2'

services:

  backend:
    build:
      context: ./
    depends_on:
      - cache
    volumes:
      - ./:/app/
    command: go run main.go mykey myvalue

  cache:
    image: memcached:alpine
